<?php
require_once __DIR__ . '/_layout.php';
$sid = $student['id'];

/* ---- Printable receipt ---- */
$viewId = (int)($_GET['receipt'] ?? 0);
if ($viewId) {
    $stmt = db()->prepare(
      "SELECT p.*, c.title AS course_title FROM payments p
       LEFT JOIN courses c ON c.id=p.course_id
       WHERE p.id=? AND p.student_id=? LIMIT 1"
    );
    $stmt->execute([$viewId, $sid]);
    $pay = $stmt->fetch();
    if (!$pay) { redirect('student/payments.php'); }
    require __DIR__ . '/../includes/receipt.php';
    render_receipt($pay, $student);
    exit;
}

/* ---- List ---- */
$pays = db()->prepare(
  "SELECT p.*, c.title AS course_title FROM payments p
   LEFT JOIN courses c ON c.id=p.course_id
   WHERE p.student_id=? ORDER BY p.id DESC"
);
$pays->execute([$sid]);
$pays = $pays->fetchAll();

$total = 0; foreach ($pays as $p) { if (in_array($p['status'],['paid','partial'])) $total += $p['amount']; }

student_layout_top('payments', 'Fee Receipts');
?>

<div class="rounded-2xl bg-gradient-to-r from-brand-600 to-violet-600 text-white p-6 mb-6 flex items-center justify-between">
  <div><p class="text-white/80 text-sm">Total Paid</p><p class="font-display text-3xl font-bold"><?= money($total) ?></p></div>
  <span class="text-4xl">💳</span>
</div>

<?php if (!$pays): ?>
  <div class="rounded-2xl bg-white border border-slate-100 p-12 text-center">
    <p class="text-5xl">🧾</p>
    <p class="mt-4 text-lg font-semibold text-slate-700">No receipts yet</p>
    <p class="text-slate-500 mt-1">Fee receipts are generated by admin. They'll appear here once available.</p>
  </div>
<?php else: ?>
  <div class="rounded-2xl bg-white border border-slate-100 overflow-hidden">
    <div class="overflow-x-auto">
      <table class="w-full text-sm">
        <thead class="bg-slate-50 text-slate-500 text-left">
          <tr>
            <th class="px-5 py-3 font-semibold">Receipt No.</th>
            <th class="px-5 py-3 font-semibold">Course</th>
            <th class="px-5 py-3 font-semibold">Date</th>
            <th class="px-5 py-3 font-semibold">Mode</th>
            <th class="px-5 py-3 font-semibold">Amount</th>
            <th class="px-5 py-3 font-semibold">Status</th>
            <th class="px-5 py-3 font-semibold text-right">Action</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-slate-100">
          <?php foreach ($pays as $p):
            $badge = $p['status']==='paid' ? 'bg-emerald-100 text-emerald-700' : ($p['status']==='partial' ? 'bg-amber-100 text-amber-700' : 'bg-rose-100 text-rose-700');
          ?>
            <tr class="hover:bg-slate-50">
              <td class="px-5 py-4 font-mono text-xs"><?= e($p['receipt_no']) ?></td>
              <td class="px-5 py-4"><?= e($p['course_title'] ?? '—') ?></td>
              <td class="px-5 py-4 text-slate-500"><?= fmt_date($p['paid_on']) ?></td>
              <td class="px-5 py-4 text-slate-500"><?= e($p['mode']) ?></td>
              <td class="px-5 py-4 font-semibold text-slate-900"><?= money($p['amount']) ?></td>
              <td class="px-5 py-4"><span class="px-2.5 py-1 rounded-full text-xs font-semibold <?= $badge ?> capitalize"><?= e($p['status']) ?></span></td>
              <td class="px-5 py-4 text-right"><a href="<?= url('student/payments.php?receipt=' . $p['id']) ?>" class="font-semibold text-brand-600 hover:text-brand-700">View →</a></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  </div>
<?php endif; ?>

<?php student_layout_bottom(); ?>
